name: Deploy all
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Build
        run: |
          chmod +x ./build_all.sh
          ./build_all.sh
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: build
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

